# Generated by Django 4.2.3 on 2023-12-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subttile',
            field=models.CharField(max_length=200, verbose_name='Subtitulo'),
        ),
    ]
