# Generated by Django 4.2.3 on 2024-01-15 19:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
